docker:
  run:
    image: golang:1.9-alpine
    volumes:
      - '"$PWD":/go/src/github.com/fudanchii/monocle'
    workdir: /go/src/github.com/fudanchii/monocle
    env:
      - GOPATH=/go
    steps: |
      ./updeps
      go build -v
