variables:
  eval:
    shortRev: git rev-parse --short HEAD

docker:
  run:
    image: quay.io/fudanchii/go:1.9
    volumes:
      - .:/go/src/github.com/fudanchii/monocle
    workdir: /go/src/github.com/fudanchii/monocle
    steps: |
      set -x
      ./updeps
      ginkgo -tags static ./...
      go build -a -tags "static netgo" -ldflags "-extldflags '-static'"
      cp -f monocle .build/

  build:
    root: .build
    tags:
      - quay.io/fudanchii/monocle:{{.Eval.shortRev}}
      - quay.io/fudanchii/monocle:latest
    push:
      registry: quay.io
