docker:
  run:
    image: golang:1.9
    volumes:
      - .:/go/src/github.com/fudanchii/monocle
    workdir: /go/src/github.com/fudanchii/monocle
    env:
      - GOPATH=/go
    steps: |
      apt-get update -y
      apt-get install -y --no-install-suggests --no-install-recommends \
        ca-certificates \
        make \
        gcc \
        cmake \
        git

      ./updeps
      go build -tags static
