docker:
  run:
    image: quay.io/fudanchii/go:1.9
    volumes:
      - .:/go/src/github.com/fudanchii/monocle
    workdir: /go/src/github.com/fudanchii/monocle
    steps: |
      set -x
      ./updeps
      ginkgo -tags static tests
      go build -tags static
      cp -f monocle .build/

  build:
    root: .build
    tags:
      - quay.io/fudanchii/monocle:latest
    push:
      registry: quay.io
