#!/usr/bin/env sh

export PATH=$GOPATH/bin:$PATH

set -e

if [ -z "$NODEP" ]; then
    go get github.com/rancher/trash
    trash -k $@
fi

cd vendor/github.com/libgit2/git2go
mkdir -p vendor

if [ ! -d vendor/libgit2 ]; then
    git clone https://github.com/libgit2/libgit2 vendor/libgit2
fi

script/build-libgit2-static.sh
go build -tags static
